version: '3.4'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
      - 8443:8443
      - 4443:4443
      - 8743:8743
      - 9443:9443
      - 4943:4943
    volumes:
      - $PWD/nginx/nginx.conf:/etc/nginx/nginx.conf
      - $PWD/ssl:/home/ubuntu/apps/cert-quentify/
